title: My Blog
name: "소프트웨어학부 20223135 정민용"
email: my2002629@kookmin.ac.kr
description: Hello World
url: "https://jmy-github.github.io/"
repository: "JMY-Github.github.io"
github_username: JMY-Github

# Build settings
theme: minima
plugins:
  - jekyll-feed
